### GET Root
GET http://localhost:8080/
Accept: application/json


### GET All Cash Flow
GET http://localhost:8080/cashflow
Accept: application/json


### GET Cash Flow by ID
GET http://localhost:8080/cashflow/1
Accept: application/json


### ADD New Cash Flow
POST http://localhost:8080/cashflow/add?type=Expense&amount=75000&description=Ngopi%20bareng
Accept: application/json


### DELETE Cash Flow by ID
DELETE http://localhost:8080/cashflow/2
Accept: application/json


### GET Cash Flow Summary
GET http://localhost:8080/cashflow/summary
Accept: application/json
